### ISSUE TITLE
11月20日走查问题

### ISSUE THREAD

**Issue by linwenjun** [emagrorrim/TW_Homework4#1]
https://github.com/emagrorriM/TW_Homework4/blob/master/code/JS/main.js#L60-L73
为什么不用jquery的ajax

**Comment by linwenjun** [comment]
好多地方可以用jquery，写成了原生js
https://github.com/emagrorriM/TW_Homework4/blob/master/code/JS/main.js#L37-L58
可以用jquery的相应接口，若喜欢写原生代码，则下面这句也写成原生的，保持统一风格
https://github.com/emagrorriM/TW_Homework4/blob/master/code/JS/main.js#L12

**Comment by linwenjun** [comment]
在输入栏中输入一个空格，会产生奇怪的变化

**Comment by emagrorrim** [comment]
problem fixed

**Comment by emagrorrim** [comment]
thx
